/**********************************************************************
 *
 *   Component hook generated by Quest
 *
 *   Code Logic for the component goes in this hook
 *   To setup bindings that use the data here or call the functions here, use the Quest editor
 *
 *   For help and further details refer to: https://www.quest.ai/docs
 *
 *
 **********************************************************************/

import React from 'react'
import { useCard7Service } from 'services/Card7'

const initialState = {
  id: 2014422,
}

const useCard7 = (props) => {
  const [card2State, setCard2State] = React.useState(initialState)
  const basicAdapter = (data) => {
    return {
      image: data?.src.original || '',
      ...data,
    }
  }

  let data = {
    ...useCard7Service(basicAdapter, card2State),
    ...card2State,
  }

  const changeImage = () => {
    setCard2State({ ...card2State, id: card2State.id + 1 })
  }

  let fns = { changeImage }
  return { data, fns }
}

export default useCard7
